# should be llvm source 
LLVM_SRC_DIR = /home/vadve/$(USER)/llvm

# project directory 
PROJ_DIR = /home/vadve/$(USER)/parse

#llvm lib
LLVM_LIB_DIR = /localhome/$(USER)/llvm/

#proj compile
PROJ_COMPILE := 1

TOPLEVEL := $(LEVEL) 
LEVEL = $(LLVM_SRC_DIR)
include $(LEVEL)/Makefile.common

