# should be llvm source 
LLVM_SRC_DIR = /home/vadve/$(USER)/llvm

#llvm lib
LLVM_LIB_DIR = /localhome/$(USER)/llvm/

#proj compile
PROJ_COMPILE := 1

PROJLEVEL := $(LEVEL) 
LEVEL = $(LLVM_SRC_DIR)
include $(LEVEL)/Makefile.common

