#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
PARALLEL_DIRS=SafePoolAllocator BoundsCheckAllocator KernelSafePoolAllocator


include $(LEVEL)/Makefile.common
