LEVEL = ../../

LIBRARYNAME=safecode

BUILD_RELINKED=1
SHARED_LIBRARY=1

include $(LEVEL)/Makefile.common

ObjectsO := $(LibDir)/addchecks.o $(LibDir)/arrayboundcheck.o $(LibDir)/indirectcalls.o $(LibDir)/speculativechecking.o $(LibDir)/convert.o $(LibDir)/pointerchecks.o $(LibDir)/stackcheck.o
ObjectsLO := $(LibDir)/addchecks.o $(LibDir)/arrayboundcheck.o $(LibDir)/indirectcalls.o $(LibDir)/speculativechecking.o $(LibDir)/convert.o $(LibDir)/pointerchecks.o $(LibDir)/stackcheck.o
