LEVEL = ../..
TOOLNAME = parse
LLVMLIBS = bcreader bcwriter instrument profpaths scalaropts \
           ipo ipa.a datastructure.a transforms target.a analysis \
	   transformutils vmcore support cwriter
USEDLIBS = arrayboundcheck.a omega_calc.a codegen.a omega.a 
TOOLLINKOPTSB = -L/home/vadve/dhurjati/libs
TOOLLINKOPTS = -ldl -lm 
include $(LEVEL)/Makefile.common

