
LEVEL = ../../

BUILD_RELINKED=1

LIBRARYNAME=arrayboundcheck

SOURCES := ABCPreProcess.cpp AffineExpressions.cpp BottomUpCallGraph.cpp ArrayBoundCheck.cpp BreakConstantGEPs.cpp

include $(LEVEL)/Makefile.common

