
LEVEL = ../../

DONT_BUILD_RELINKED=1
SHARED_LIBRARY=1
LIBRARYNAME=arrayboundcheck

SOURCES := ABCPreProcess.cpp AffineExpressions.cpp BottomUpCallGraph.cpp ArrayBoundCheck.cpp

include $(LEVEL)/Makefile.common

