
LEVEL = ../../

BUILD_ARCHIVE := 1
LIBRARYNAME=addchecks

SOURCES = GEPChecks.cpp \
          #LoadStoreChecks.cpp \
          #AlignmentChecks.cpp \
          #MonotonicLoopOpt.cpp \
          #ClearCheckAttributes.cpp \
          #RegisterBounds.cpp \
          #CompleteChecks.cpp \
          #RegisterRuntimeInitializer.cpp \
          #RegisterStackObjPass.cpp \
          #insert.cpp

include $(LEVEL)/Makefile.common

