
LEVEL = ../../

BUILD_ARCHIVE := 1
LIBRARYNAME=addchecks

SOURCES = GEPChecks.cpp \
          LoadStoreChecks.cpp \
          CFIChecks.cpp \
          RegisterBounds.cpp \
          RegisterRuntimeInitializer.cpp \
          RegisterStackObjPass.cpp \
          CompleteChecks.cpp \
          #AlignmentChecks.cpp \
          #MonotonicLoopOpt.cpp \
          #ClearCheckAttributes.cpp \
          #insert.cpp

include $(LEVEL)/Makefile.common

